### ISSUE TITLE
Could we get back signed *.asc files, please, for every release?

### ISSUE THREAD

**Issue by mcepl** [deadbeefsociety/sshfs#12]
https://github.com/deadbeefsociety/sshfs/blob/f9fd288b1bd66a334ede19336e02b648c0853d24/make_release_tarball.sh#L25

It seems like the file is generated but not uploaded anywhere.

**Comment by h4sh5** [comment]
Curious, is this a requirement for software going into SUSE? 

I have signed and re-made the release with the GPG message. 

https://github.com/deadbeefsociety/sshfs/releases/tag/sshfs-3.7.4

**Comment by mcepl** [comment]
It is not requirement, but it is certainly something we like to see.

**Comment by mcepl** [comment]
Something’s wrong:

```
tumbleweed-pkg~/b/h/sshfs (3A1D1M)$ gpg --verify sshfs-3.7.4.tar.xz.asc
gpg: assuming signed data in 'sshfs-3.7.4.tar.xz'
gpg: Signature made So 16. září 2023, 09:01:23 CEST
gpg:                using RSA key A56509CB6B3585A814B1A735C76141536EC77B36
gpg: requesting key C76141536EC77B36 from hkps://keys.openpgp.org
gpg: Can't check signature: No public key
tumbleweed-pkg~/b/h/sshfs (3A1D1M)$
```

And I cannot find key ID `0xC76141536EC77B36` neither on `keyserver.ubuntu.com`, `pgp.mit.edu`, nor on `keys.openpgp.org`.

**Comment by h4sh5** [comment]
Try again now - I've uploaded my GPG key to ubuntu keyserver, openpgp, and verified my email on `keys.openpgp.org`

**Comment by mcepl** [comment]
On Sat Sep 16, 2023 at 10:10 AM CEST, Haoxi Tan wrote:
> Try again now - I've uploaded my GPG key to ubuntu keyserver,
openpgp, and verified my email on `keys.openpgp.org`

Thank you. Works well.

Best,

Matěj

-- 
https://matej.ceplovi.cz/blog/, Jabber: ***@***.***
GPG Finger: 3C76 A027 CA45 AD70 98B5  BC1D 7920 5802 880B C9D8
 
One reason that life is complex is that it has a real part and an
imaginary part.
    -- Andrew König
